language: c
before_install:
    - sudo apt-get install device-tree-compiler gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libncurses5-dev build-essential bison flex libssl-dev bc
dist: focal
branches:
    only:
        - master
script:
    - ./tools/scripts/makeall "arm x86"
os:
    - linux
notifications:
    email:
      on_success: always
      on_failure: always
